name:                Animal
version:             0.1.0.0
github:              "githubuser/Animal"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Animal#readme>

dependencies:
- HUnit >= 1.6.1.0 && < 1.6.2.0 
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  Animal-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fglasgow-exts
    dependencies:
    - Animal

tests:
  Animal-test:
    main:                Spec.hs
    source-dirs:         
    - test
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fglasgow-exts
    dependencies:
    - HUnit
    - Animal
